accounts/urls.py
from django.contrib.auth import authenticate
from django.contrib.auth.views import LoginView
from django.urls import path , include
from accounts.forms import UserLoginForm
from accounts import views
from accounts.views import RegisterView

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('login/', LoginView.as_view(authentication_form=UserLoginForm), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', views.edit_profile, name='profile'),
    path('logout/', views.custom_logout, name='logout'),
]

projects/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ProjectListView.as_view(), name= 'project_list'),
    path('project/create/', views.ProjectCreateView.as_view(), name= 'project_create'),
    path('project/edit/<int:pk>', views.ProjectUpdateView.as_view(), name= 'project_update'),
    path('project/delete/<int:pk>', views.ProjectDeleteView.as_view(), name='project_delete'),
    path('task/create/', views.TaskCreateView.as_view(), name='task_create'),
    path('task/edit/<int:pk>/', views.TaskUpdateView.as_view(), name='task_update'),
    path('task/delete/<int:pk>', views.TaskDeleteView.as_view(), name='task_delete'),
]

projects_management/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.utils.translation import gettext_lazy as _

admin.site.site_header = _('Projects Management')
admin.site.site_title = _('Projects Management')


urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('PmAdmin/', admin.site.urls),
    path('', include('projects.urls')),
    path('accounts/', include('accounts.urls')),
]

projects/models.py
from django.db import models
from django.conf import settings
from django.utils.translation import gettext_lazy as _


# Create your models here.

class Category(models.Model):
    name= models.CharField(max_length= 255)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Category')

class ProjectStatus(models.IntegerChoices):
    PENDING= 1, _('Pending')
    COMPLETED= 2, _('Completed')
    POSTPONED= 3, _('Postponed')
    CANCELED= 4, _('Canceled')

class Project(models.Model):
    title= models.CharField(max_length=255)
    description= models.TextField()
    status = models.IntegerField(choices=ProjectStatus.choices, default=ProjectStatus.PENDING)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('Project')
        verbose_name_plural = _('Project')

class Task(models.Model):
    description= models.TextField()
    is_completed= models.BooleanField(default=False)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    def __str__(self):
        return self.description

    class Meta:
        verbose_name = _('Task')
        verbose_name_plural = _('Task')

projects/forms.py
from dataclasses import fields

from django import forms

from . import models
from django.utils.translation import gettext_lazy as _


attrs = {'class': 'form-control'}

class ProjectCreateForm(forms.ModelForm):
    class Meta:
        model = models.Project
        fields = ['category', 'title', 'description',]
        labels = {
            'category': _('Category'),
            'title': _('Title'),
            'description': _('Description'),
        }
        widgets={
            'category': forms.Select(attrs=attrs),
            'title' : forms.TextInput(attrs=attrs),
            'description' : forms.Textarea(attrs=attrs),
        }

class ProjectUpdateForm(forms.ModelForm):
    class Meta:
        model = models.Project
        fields = ['category', 'title', 'status',]
        widgets={
            'category': forms.Select(attrs=attrs),
            'title' : forms.TextInput(attrs=attrs),
            'status' : forms.Select(attrs=attrs),
        }

projects/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from . import models, forms
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from projects.models import Project

# Create your views here.
class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = 'project/list.html'
    paginate_by = 6

    def get_queryset(self):
        query_set = super().get_queryset()
        where = {'user_id': self.request.user}
        q = self.request.GET.get('q', None)
        if q:
            where['title__icontains'] = q
        return query_set.filter(**where)


class ProjectCreateView(LoginRequiredMixin,CreateView):
    model= models.Project
    form_class = forms.ProjectCreateForm
    template_name = 'project/create.html'
    success_url = reverse_lazy('project_list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class ProjectUpdateView(LoginRequiredMixin,UserPassesTestMixin, UpdateView):
    model = models.Project
    form_class = forms.ProjectUpdateForm
    template_name = 'project/update.html'

    def test_func(self):
        return self.get_object().user_id == self.request.user.id

    def get_success_url(self):
        return reverse('project_update', args=[self.object.id])

class ProjectDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = models.Project
    template_name = 'project/delete.html'
    success_url = reverse_lazy('project_list')

    def test_func(self):
        return self.get_object().user_id == self.request.user.id

class TaskCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = models.Task
    fields = ['project', 'description']
    http_method_names = ['post']

    def test_func(self):
        project_id= self.request.POST.get('project', '')
        return models.Project.objects.get(pk=project_id).user_id == self.request.user.id

    def get_success_url(self):
        return reverse('project_update', args=[self.object.project.id])

class TaskUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = models.Task
    fields = ['is_completed']
    http_method_names = ['post']

    def test_func(self):
        return self.get_object().project.user_id == self.request.user.id

    def get_success_url(self):
        return reverse('project_update', args=[self.object.project.id])

class TaskDeleteView(LoginRequiredMixin, UserPassesTestMixin,  DeleteView):
    model = models.Task

    def test_func(self):
        return self.get_object().project.user_id == self.request.user.id

    def get_success_url(self):
        return reverse('project_update', args=[self.object.project.id])

projects/templates/project/create.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="card col-md-6 px-0">
                <div class="card-header">
                    <h3 class="mb-0 py-2">{% trans "New Project" %}</h3>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% include "common/form.html" with form=form %}
                        <button class="btn btn-success">
                            {% trans "Create" %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

projects/templates/project/delete.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <h2>{% trans 'Alert' %}</h2>
    <form action="" method="post">{% csrf_token %}
        <p class="text-muted my-4">{% trans 'Are you sure to delete' %} "{{ project.title }}"?</p>
        <button class="btn btn-danger" type="submit">{% trans 'Delete' %}</button>
    </form>
{% endblock %}

projects/templates/project/list.html
<!-- projects/templates/projects/list.html -->
{% extends "base.html" %}
{% load i18n %}
{% load humanize %}

{% block content %}

    <div class="d-flex">
        <h3 class="me-auto">{% trans 'My Projects' %}</h3>
        <div>
            <a href="{% url 'project_create' %}" class="btn btn-outline-success">
                <i class="bi bi-plus-lg "></i> {% trans 'New Project' %}
            </a>
        </div>
    </div>

    <div class="row my-5">
        {% for project in object_list %}
            <div class="col-md-4">
                <div class="card mb-3">
                    <div class="card-body">
                        <p>
                            <span class="badge rounded-pill bg-dark">
                                {{ project.get_status_display }}
                            </span>
                        </p>
                        <h3 class="card-title fs-6">
                            {{ project.title }}
                        </h3>
                        <p class="card-text text-muted small">
                            {{ project.description }}
                        </p>
                        <div class="d-flex">
                            <span class="me-auto text-muted small">
                                <i class="bi bi-clock"></i>
                                <time datetime="{{ project.created_at }}">
                                    {{  project.created_at|naturaltime }}
                                </time>
                            </span>
                            <a
                                href="{% url 'project_update' project.id %}"
                                class="btn btn-sm btn-outline-dark mx-1">
                                {% trans 'Edit' %}
                            </a>
                            <a
                                href="{% url 'project_delete' project.id %}"
                                class="btn btn-sm btn-outline-danger">
                                <i class="bi bi-trash"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        {% empty %}
            <div class="col-md-12">
                <div class="h-100 p-5 bg-white border rounded-3 text-center">
                    <p>{% trans 'There is no projects to show' %}</p>
                    <p>
                        <i class="bi bi-emoji-frown fs-1"></i>
                    </p>
                    <a class="btn btn-success" type="button" href="{% url 'project_create' %}">
                        <i class="bi bi-plus-lg "></i> {% trans 'New Project' %}
                    </a>
                </div>
            </div>
        {% endfor %}
        {% if page_obj.paginator.count > 0 %}
            <div class="d-flex justify-content-center bd-highlight mb-3">
                <nav>
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                                    {% trans 'Previous' %}
                                </a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" href="#">{% trans 'Previous' %}</a>
                            </li>
                        {% endif %}
                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                                    {% trans 'Next' %}
                                </a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" href="#">{% trans 'Next' %}</a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        {% endif %}
    </div>

{% endblock %}

projects/templates/project/task.html
{% load i18n %}

<ul class="list-group">
    {% for task in object.task_set.all %}
        <li class="list-group-item d-flex">
            <form action="{% url 'task_update' task.id %}" method="POST" class="my-auto me-2">
                {% csrf_token %}
                <input
                    class="form-check-input"
                    type="checkbox"
                    name="is_completed"
                    {% if task.is_completed %} checked {% endif %}
                    onchange="this.form.submit()"/>
            </form>
            <p class="my-auto me-auto">
                {{ task.description }}
            </p>
            <form action="{% url 'task_delete' task.id %}" method="POST">
                {% csrf_token %}
                <button class="btn" type="submit"><i class="bi bi-trash text-danger"></i></button>
            </form>
        </li>
    {% endfor %}
</ul>
<div class="card mt-2">
    <div class="card-body">
        <form method="POST" action="{% url 'task_create' %}" class="d-flex">
            {% csrf_token %}
            <div class="input-group">
                <input type="hidden" value="{{ object.id }}" name="project"/>
                <input type="text" name="description" class="form-control" placeholder="{% trans 'New Task' %}" required />
                <button class="btn btn-outline-dark" type="submit">{% trans 'Add' %}</button>
            </div>
        </form>
    </div>
</div>

projects/templates/project/update.html
{% extends "base.html" %}
{% load humanize %}
{% load i18n %}

{% block content %}

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">
                <h5>
                    {{ object.title }}
                </h5>
            </li>
        </ol>
    </nav>

    <div class="row">
        <div class="col-md-3">
            <form method="POST">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="mb-3">
                                {{ field }}
                            </div>
                        {% endfor %}
                        <div class="d-flex mt-2">
                            <span class="me-auto text-muted small">
                                <i class="bi bi-clock"></i>
                                <time datetime="{{ project.created_at }}">
                                    {{ object.created_at|naturaltime }}
                                </time>
                            </span>
                        </div>
                    </div>

                        <div class="card-footer">
                            <div class="d-grid gap-2">
                                <button class="btn btn-success">
                                    <i class="bi bi-save"></i>
                                    {% trans 'Save' %}
                                </button>
                                <a class="btn btn-danger" href="{% url 'project_delete' object.id %}">
                                    <i class="bi bi-trash"></i>
                                    {% trans 'Delete' %}
                                </a>
                            </div>
                        </div>
                </div>
            </form>
        </div>
        <div class="col-md-9 mt-2 mt-md-0">
{#            {% include 'projects/project_task_stats.html' with project=object %}#}
            {% include 'project/task.html' with project=object %}
        </div>
    </div>
{% endblock %}